name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Install MAUI workload
      run: dotnet workload install maui
      
    # Configurazione Firebase per Android
    - name: Setup Firebase configuration for Android
      run: |
        mkdir -p Platforms/Android
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > Platforms/Android/google-services.json
        
        # Verifica che il file sia stato creato correttamente
        if (Test-Path -Path "Platforms/Android/google-services.json") {
          Write-Host "Firebase Android configuration file created successfully"
        } else {
          Write-Error "Failed to create Firebase Android configuration file"
          exit 1
        }
    
    # Configurazione Firebase generale
    - name: Create Firebase config file
      run: |
        echo "${{ secrets.FIREBASE_CONFIG }}" > firebase-config.json
        
        # Verifica che il file sia stato creato correttamente
        if (Test-Path -Path "firebase-config.json") {
          Write-Host "Firebase general configuration file created successfully"
        } else {
          Write-Error "Failed to create Firebase general configuration file"
          exit 1
        }
      
    - name: Restore dependencies
      run: dotnet restore ClimbTrack.sln
      
    - name: Build
      run: dotnet build ClimbTrack.sln --configuration Release --no-restore
      
    # Se hai test unitari, aggiungi questo step
    # - name: Test
    #   run: dotnet test ClimbTrack.sln --configuration Release --no-build
    
    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-packages
        path: |
          bin/Release/net9.0-android/**/*.apk
          bin/Release/net9.0-windows10.0.19041.0/**/*.msix